# This is the full, final URL for your blog once it's deployed.
baseURL = "/"

# This new line forces all links to be absolute, fixing the CSS path.
canonifyURLs = true

languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  centerTheme = true
  readingTime = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Sarim's Tech Blog"
    subtitle = "A simple retro themed by Sarim"
    copyright = "© 2025 Sarim"

    [languages.en.params]
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"

      [languages.en.params.logo]
        logoText = "Sarim's Blog"
        logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "All Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Portfolio"
        url = "http://exc33ded.github.io/portfolio"